# Generated by Django 4.1.7 on 2023-04-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_delete_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
    ]
